### ISSUE TITLE
Where is the code for perception? 

### ISSUE THREAD

**Issue by haotang1995** [stevenlsw/physgen#2]
Hi there, thanks for sharing the code for simulation and rendering. However, I couldn't find the code for perception, which is the most interesting part from my perspective, especially the part letting GPT-4 extract sim.yaml for us. Could you please help share the code for perception as well? Thanks!

**Comment by stevenlsw** [comment]
Hi,

Thanks for you interest. I am cleaning and will update the perception
module and readme very soon within this week.

Best,
Shaowei

**Comment by stevenlsw** [comment]
Hi, 

We have push all modules in perception. Please let me know if you have any other questions.

**Comment by haotang1995** [comment]
Hi Shaowei,

Thanks for sharing the code! I did check it about two days ago. It's kind of a pity that the current version still cannot generate consistent interpretable e.g., object labels (with movable flag) and the global gravity if I understand the code correctly (I tried the "balls" example). But the rendering part is still interesting and attractive. Thanks for sharing the code anyway!

Best,
Tang, Hao

**Comment by stevenlsw** [comment]
Hi, Hao,

Could you elaborate more which object  is not working with the movable
prediction? For gravity, it is quite straightforward to set 980 for side
view images and not for top-down view.

**Comment by haotang1995** [comment]
Yeah, I tried the "balls" example and ran `gpt_ram` on it. It will output things like: `{"stone": true, "circle": false, "line": false}` in `intermediate/obj_movable.json`, which should be fine although not so interpretable. I then ran `run_gsam` and got movable objects for the bottom left two stones. 
![image](https://github.com/user-attachments/assets/acc8b522-c20a-48d2-b41d-eb36a9e409de)
For inconsistency, I mean `gpt_ram` can also output things like `{"curlingstone": true, "house": false, "logo": false}` for different runs. I guess there is no way to determine which output is better for now?

**Comment by stevenlsw** [comment]
Hi Hao,

I see the issue, GPT-4V sometimes will output different results in
different runs based on its manner.  Alternatively, you could also use
[ram](https://github.com/xinyu1205/recognize-anything) to recognize the
objects in the image and ask GPT-4V to predict movability to avoid
randomness in each run of GPT-4V.

Best,
Shaowei
