### ISSUE TITLE
Dataset for evaluation

### ISSUE THREAD

**Issue by asdjia** [stevenlsw/physgen#5]
Hi,

Thank you for your excellent work. May I kindly ask if you could share the dataset mentioned on page 10 of the paper that you used in this work?

Thank you!

**Comment by stevenlsw** [comment]
Hi, 

Thanks for your interest, we will upload the dataset and testing images soon.

**Comment by stevenlsw** [comment]
Hi, 

I update the evaluation module, the detailed instructions can be found [here](https://github.com/stevenlsw/physgen?tab=readme-ov-file#evaluation). Please let me know if you have any other questions.
