### ISSUE TITLE
Valid Mask

### ISSUE THREAD

**Issue by KangLiao929** [stevenlsw/physgen#6]
Hi there, thanks for sharing the code and data.

Could you please provide the valid mask of each sample? Currently, I found most masks are invalid in the shared ```data``` folder.

Thanks!

**Comment by stevenlsw** [comment]
Hi, could you elaborate more what does mask invalid means? you could also refer to the [segmentation module](https://github.com/stevenlsw/physgen/tree/main/perception#segmentation) in the repo to get the mask.

**Comment by KangLiao929** [comment]
> Hi, could you elaborate more what does mask invalid means? you could also refer to the [segmentation module](https://github.com/stevenlsw/physgen/tree/main/perception#segmentation) in the repo to get the mask.

It works for me now. Thanks!
